"""Adventures v1.1: package content and reviewed original sources."""
from pathlib import Path
from html import escape as e
import json

def install(ed):
    d=json.loads((Path(__file__).resolve().parents[1]/'adventures.json').read_text())
    P,add,link,para,section,table,steps,listing=ed.P,ed.add,ed.link,ed.para,ed.section,ed.table,ed.steps,ed.listing
    def gift_text(g):
        return f"{g['gil']:,} gil + choose ONE: "+' OR '.join(f"{c['quantity']} {e(c['name'])}" for c in g['choices'])
    status='Adventures v1.1 package ready and tested offline. Installation and in-game play are not yet confirmed.'
    start=steps('Talk to Zenith Armsmith near Home Point #1 in Northern San d’Oria, out of combat.','Choose Your next adventure. Select Goals for your job, Hunt contracts or Explore.','Read the named objective and reward, then choose Start. Progress begins after acceptance.','Check My progress at the Armsmith, or Adventure progress at either Zenith Scout. Claim earned hunt and route rewards at the Armsmith.')
    add('adventures','Your Next Adventure','Guides','Choose a useful goal, take an optional hunt, or explore a short route at your own pace.',
        section('Start here',start)+section('Choose an activity',table(['Activity','What you do','What you earn'],[
        (link('adventure-goals','Goals for your job'),'Pin an equipment option, original quest or NM goal.','The original item or quest reward, obtained through normal play.'),
        (link('hunt-contracts','Hunt contracts'),'Defeat the exact named monster in its listed zone.','Gil scaled to the hunt, plus one chosen gift: food, medicine or crafting supplies.'),
        (link('exploration-routes','Exploration routes'),'Visit three named landmarks in order. Each visit records automatically.','Gil plus a choice of original Mog House furnishings.')]))+
        section('At WAR27',para('Clipper in Qufim is an available normal hunt: defeat six for 1,500 gil plus your choice of 12 Meat Mithkabobs or 12 Melon Pies. Valkurm Coast is the first exploration route. These are separate from Hands That Guard; a Clipper kill can advance both when both are accepted and their requirements are met.'))+
        section('Progress and rewards',listing(['One active hunt and one active route at a time. A pinned goal is separate.','There are no deadlines, daily resets or missed-day penalties. Pause keeps your progress; Resume continues it.','Progress belongs to the character and survives job changes. Fight or explore on a main job meeting the displayed level.','Each contract and route pays once per character. Completed entries remain under All / completed.','Leave one inventory slot free when claiming. If your bag is full, progress stays saved.','The original monsters and their loot remain unchanged. Hunt milestone gifts are separate once-per-character bonuses.'])),
        facts=[('Start',link('zenith-armsmith','Zenith Armsmith')),('Hunts','16'),('Routes','2'),('Time limit','None')],parent='quests',status=status)
    rows=[]
    for r in sorted(d['contracts'],key=lambda r:(r['level'],r['id'])):
        rows.append((r['level'],e(r['name'])+(' <strong>Hard</strong>' if r['hard'] else ''),e(r['area']),f"{r['monsterLow']}–{r['monsterHigh']}",r['count'],gift_text(r['gift']),e(r['hint'])))
    add('hunt-contracts','Hunt Contracts','Quests','Pick one named hunt, finish it when you like, and collect gil plus a gift you choose.',
        section('How to play',steps('Open Your next adventure → Hunt contracts at Zenith Armsmith.','Choose a hunt, read its zone and enemy levels, then Start. The first list highlights up to five eligible unfinished hunts; All / completed shows the full list.','Defeat the specified monsters in that zone while alive, within 50 yalms and on a main job at the listed minimum level. Party and Trust assistance are allowed.','Read the counter after each qualifying kill. Return to Armsmith when the hunt is complete, choose Claim reward, then choose ONE of its two gifts. The displayed gil is included.'))+
        section('All sixteen hunts',table(['Main level','Monster','Zone','Enemy level','Defeat','Reward','Where / preparation'],rows))+
        section('Take a break',para('Open your active hunt and choose Pause before starting a different one. The previous count is kept. Resume it later. Counts do not reset at midnight or when you change jobs.'))+
        section('If a kill does not count',listing(['Accept the contract before fighting.','Check the exact monster name and zone; similar monsters elsewhere and fished versions are not included.','Meet the main-job level, stay alive and nearby, and ensure your party receives the kill.','A completed contract cannot be farmed for another reward.']))+
        para(link('adventures','Back to Your Next Adventure')),parent='adventures',status=status)
    def map_figure(route):
        name='valkurm-dunes' if route['zone']==103 else 'qufim-island'
        markers=[]
        for i,p in enumerate(route['points'],1):
            col,row=p['grid'].split('-');x=16+(ord(col)-65)*32;y=16+(int(row)-1)*32
            markers.append(f'<span class="scout-marker" style="left:{x/512*100}%;top:{y/512*100}%;width:6.25%;height:6.25%;display:grid;place-items:center;color:#fff;background:rgba(125,20,20,.6);font-weight:bold" aria-hidden="true">{i}</span>')
        source='Valkurm_Dunes' if route['zone']==103 else 'Qufim_Island'
        return '<figure class="scout-map"><div class="map-marked"><img src="assets/maps/'+name+'.png" width="512" height="512" alt="'+e(route['name'])+' map: numbered grid cells match the stop table below" loading="lazy">'+''.join(markers)+'</div><figcaption>Numbers show the documented map squares, not exact NPC pins. Follow the named landmarks below. Original game map © SQUARE ENIX; existing image credits retained. <a href="https://horizonffxi.wiki/'+source+'">Zone map reference</a>.</figcaption><button type="button" data-enlarge-map>Enlarge marked map</button></figure>'
    body=section('How visits work',steps('At Zenith Armsmith, choose Your next adventure → Explore, select a route and Start.','Visit the stops in order while alive and out of combat, on a main job meeting the route level. Stand near the named landmark for a few seconds.','The chat records Visited, your count and the next stop. Entering a nearby zone is not required.','After all three stops, return to Armsmith, choose Claim reward, then select ONE furnishing. The displayed gil is included.'))
    for r in d['routes']:
        body+=section(r['name']+' — main level '+str(r['level'])+'+',para(e(r['hint'])+' Reward: '+gift_text(r['gift'])+', once per character.')+map_figure(r)+table(['Stop','Landmark','Map square'],[(i,e(p['name']),p['grid'])for i,p in enumerate(r['points'],1)]))
    body+=section('Before leaving',listing(['Prepare Trusts and travel supplies for hostile areas. Meeting the minimum level does not make every nearby monster safe.','Approach entrance landmarks from the listed route’s zone. If you cross a zoneline first, return to that zone and approach again.','Pause preserves completed stops. After zoning or logging in, the next pending stop resumes automatically.','These are existing locations. The package adds no new NPC, map obstacle or teleport destination.']))+para(link('adventures','Back to Your Next Adventure'))
    add('exploration-routes','Exploration Routes','Quests','Two short journeys through existing landmarks, with automatic saved visits and a clear next stop.',body,parent='adventures',status=status)
    questrows=[(r['level'],e(r['name']),e(r['npc']+' · '+r['area']),e(r['task']),e(r['reward']))for r in d['nativeQuests']]
    nmrows=[(r['level'],e(r['name']),e(r['area']+' · '+r['grid']),f"{r['monsterLow']}–{r['monsterHigh']}",e(r['itemName']),e(r['hint']))for r in d['nms']]
    add('adventure-goals','Goals for Your Job','Guides','A short list of equipment options, original quests and optional NM goals for your current job and level.',
        section('Pin one goal',steps('Choose Your next adventure → Goals for your job at Zenith Armsmith.','Open Equipment, Native quest or NM challenge. Read the source, objective and reward.','Choose Pin this goal. Review it under My pinned goal, My progress, or Adventure progress at either Scout.','Acquire the item or finish the original quest. The pinned record recognises an owned item or completed quest; Clear pin removes only the reminder.'))+
        section('Equipment options',para('The guide draws from 448 original equipment records in the existing market catalogue. It offers up to three unowned pieces your current main job can equip, across different slots. It prioritises higher equip levels and a usual weapon type for your job. Ranged weapons and ammunition are outside this first shortlist.'))+
        para('An option is not a promise of better stats. Compare it with your equipment, then search its exact name at the Auction House. Stock depends on listings. Choosing or pinning a goal grants no item.')+
        section('Original quest reminders',para('The guide suggests these five quests and hides completed quests or later chapters whose predecessor is unfinished. Levels below are recommendation thresholds for the guide. The original NPC still checks the quest’s actual requirements, accepts trades and grants the original reward.')+table(['Suggested from','Quest','Contact','Task','Original reward'],questrows))+
        section('Optional NM goals',para('These appear only when you meet the recommendation level, your job can equip the native drop, and the item is not found in your bags. Lottery spawns and random drops can take time. Check your party’s readiness before fighting.')+table(['Suggested from','NM','Location','Enemy level','Native drop','Preparation'],nmrows))+
        para('The pinned Zenith source lists Empress Hairpin for Valkurm Emperor. A different private server’s Emperor Hairpin table is not used for this package.')+
        para(link('adventures','Back to Your Next Adventure')),parent='adventures',status=status)
    milestone_rows=[]
    for r in d['milestones']:
        milestone_rows.append((r['required'],f"{r['gift']['gil']:,} gil",'<br>'.join(e(c['name'])+f" · Equip Lv.{c['level']} · "+e(c['stats']) for c in r['gift']['choices'])))
    P['hunt-contracts']['body']+=section('Milestone gifts: 6, 10 and 16 hunts',para('Finish different hunt contracts, then choose Your next adventure → Hunt milestone gifts. Receive the displayed gil and ONE equipment choice at each milestone. These bonuses are earned once per character. Earlier v1.0 completions count; you do not need to repeat those kills.')+table(['Different hunts finished','Gil included','Choose ONE item'],milestone_rows))
    upgrade=para('Already finished a hunt or route in Adventures v1.0? Your recorded completion qualifies for the new v1.1 gift once, in addition to the supplies already received. Open All / completed, choose the completed activity, then Claim reward. An unfinished activity keeps its count. A delivery already flagged for review is not automatically retried.')
    P['adventures']['body']+=section('Inventory: 80 slots',para('Adventures v1.1 expands the main Inventory to 80 at login for new and existing characters. Existing items stay in place. Bag-upgrade quests are no longer needed and have been removed from the goal list. '+link('inventory','Inventory guide')+'.'))+section('Already played v1.0?',upgrade)+section('Extra hunt rewards',para('Complete 6, 10 and 16 different contracts for '+link('hunt-contracts','milestone equipment choices')+'.'))
    P['hunt-contracts']['body']+=section('Upgrading from v1.0',upgrade)
    add('inventory','Inventory','Guides','An 80-slot main Inventory, with no bag-upgrade errands after Adventures v1.1.',
        section('How it works',steps('Install Adventures v1.1 with the server stopped. It supports the previous Adventures package and the reviewed server without Adventures installed.','Start the server and log in. An existing main Inventory below 80 expands to 80 automatically. New characters receive the same capacity during their first login.','Continue playing with your existing items and quest progress. No trade, fee or GM command is required.'))+
        section('What changes',para('The update changes main Inventory capacity. It does not replace items, relocate them or enlarge other storage containers. Bag-upgrade reminders are removed from the Adventure guide. Original story and limit-break quests remain.'))+
        section('Current status',para('The player reported a 50-slot starting bag before this update. The new 80-slot behavior is implemented and tested offline; installation and the in-game capacity display have not yet been confirmed.'))+
        section('Rollback',para('Rolling back the package restores its prior files while retaining earned rewards, saved activity progress and any inventory capacity already granted. It does not shrink the bag.')),
        facts=[('Main Inventory','80 after login with v1.1'),('Applies to','New and existing characters'),('Bag quest required','No')],parent='getting-started',status=status)
    P['getting-started']['body']+=section('Carry more from the beginning',para(link('inventory','80-slot Inventory')+' is included in Adventures v1.1. Existing characters receive it at their next login after installation.'))
    P['server-rules']['body']+=section('Inventory convenience',para(link('inventory','Main Inventory: 80 slots')+' after Adventures v1.1 is installed. Bag errands are removed from the custom goal guide.'))
    for key in ('adventurer-log','zenith-armsmith','zenith-scout','quests','getting-started'):
        P[key]['body']+=section('Optional Adventures',para(link('adventures','Your Next Adventure')+' adds job goals, sixteen hunts and two exploration routes. Start and claim at Zenith Armsmith; either Scout shows progress. Requires Adventures v1.1.'))
    P['index']['body']=section('New optional adventures',para(link('adventures','Your Next Adventure')+' · '+link('hunt-contracts','Hunt Contracts')+' · '+link('exploration-routes','Exploration Routes')+' · '+link('adventure-goals','Job Goals')))+P['index']['body']
    P['roadmap']['body']=section('Approved and packaged: Adventures v1.1',para('The approved job goals, optional hunts and exploration routes are now included in one prepared installer. '+link('adventures','Read the content and rules')+'. Installation and in-game use remain unconfirmed.'))+P['roadmap']['body']
    P['update-log']['body']=section('19 September: Adventures v1.1 prepared',para('Added automatic 80-slot main Inventory, removed four bag-upgrade reminders, replaced the uniform oil/powder payouts with gil and explicit gift choices, and added three hunt-completion milestones. Prior completions retain their progress and can claim the new gifts once. Three features: job and level goals, sixteen optional hunt contracts and two automatic exploration routes. Added one Armsmith menu entry and Scout progress access. Offline LuaJIT checks covered saved counts, menu limits, reward retry/replay handling, routes and all twenty jobs. Twenty-seven installer scenarios covered fresh installs and v1.0 upgrades, supported text/encoding variants, failures and rollback. No live installation or in-game play is claimed. '+link('adventures','Full guide')+'.'))+P['update-log']['body']
    P['sources']['body']+=section('Adventures v1.1',para('Native spawn IDs, levels, loot and positions were read from the pinned LandSandBoat source snapshot f45ab5c0aa3607b4b8fb694da58434e4dd29a2e4. Gear uses native equipment/job masks and the existing 689-item Zenith market catalogue; 448 equipment records are included. Quest reminders were checked against original Jeuno quest scripts. Native-data hashes and offline test results accompany the installer. Inventory uses the native getContainerSize/changeContainerSize API and a positive delta only. Reward IDs, quantities, equipment levels and displayed stats were checked against native item SQL. Map grid references are linked beside each route; highlights identify cells, not an inferred coordinate conversion.'))
