"""Native Eldieme solo-access guide; verified against reviewed server source."""
def install(ed):
 P=ed.P; add,section,para,table,link,steps=ed.add,ed.section,ed.para,ed.table,ed.link,ed.steps
 quest='the-eldieme-necropolis-door-quest';ki='magicked-astrolabe';npc='churano-shurano'
 sources=section('Sources',para('<a href="https://www.bg-wiki.com/ffxi/Magicked_astrolabe">BG Wiki: key item</a> · <a href="https://ffxiclopedia.fandom.com/wiki/The_Eldieme_Necropolis_Door_Quest">FFXIclopedia: door quest and map location</a> · <a href="https://github.com/LandSandBoat/server/blob/f45ab5c0aa3607b4b8fb694da58434e4dd29a2e4/scripts/zones/Windurst_Waters/npcs/Churano-Shurano.lua">Reviewed NPC source</a> · <a href="https://github.com/LandSandBoat/server/blob/f45ab5c0aa3607b4b8fb694da58434e4dd29a2e4/scripts/zones/The_Eldieme_Necropolis/globals.lua">Reviewed gate source</a>'))
 add(quest,'The Eldieme Necropolis Door Quest','Quests','Buy the permanent key item that lets you open Eldieme intersection gates on your own.',section('Quest overview',table(['Starting NPC','Quest','Reward'],[(link(npc,'Churano-Shurano')+' · Windurst Waters North (F-8)','The Eldieme Necropolis Door Quest',link(ki,'Magicked Astrolabe')+' — permanent key item')]))+section('Requirements',para('Bring 10,000 gil. The reviewed NPC script has no level, fame or mission prerequisite. This unlisted side quest does not appear in the quest log.'))+section('Walkthrough',steps('Travel to the north section of Windurst Waters.','Go to the roof of the Optistery at (F-8). Churano-Shurano stands by the telescope.','Speak to Churano-Shurano and accept the offer to buy the astrolabe. Complete the dialogue with at least 10,000 gil. You do not trade an inventory item.','Check Permanent Key Items for Magicked Astrolabe. The purchase deducts 10,000 gil.','In The Eldieme Necropolis, examine a closed intersection gate to open it yourself. Pass through promptly; the reviewed script opens it for eight seconds.'))+section('How it helps',para('Useful for solo travel through Eldieme during '+link('first-limit-break','In Defiant Challenge')+' and other quests or missions that use its gated rooms. It does not award Ancient Papyrus, complete a mission or bypass other quest requirements.'))+section('If you cannot buy it',para('Check that you have 10,000 gil and do not already own the key item. If you declined the first offer, speak to the NPC again. The key item is permanent and does not occupy a normal inventory slot.'))+sources,facts=[('NPC','Churano-Shurano'),('Location','Windurst Waters North (F-8), Optistery roof'),('Cost','10,000 gil'),('Reward','Magicked Astrolabe'),('Repeatable','No')],parent='quests')
 add(ki,'Magicked Astrolabe','Key Items','A permanent key item for opening Eldieme intersection gates without a second player.',section('Obtained from',table(['NPC','Game-map location','Cost'],[(link(npc,'Churano-Shurano'),'Windurst Waters North (F-8), roof of the Optistery','10,000 gil')]))+section('How to obtain it',para(link(quest,'Full purchase walkthrough')+'. Talk to the NPC and purchase it through the dialogue.'))+section('Use',para('Examine a closed intersection gate in The Eldieme Necropolis. The gate opens briefly while you retain the key item. No Auction House purchase, crafting recipe or monster drop is involved.'))+section('Related guide',para(link('first-limit-break','First Limit Break: Ancient Papyrus hunt')))+sources,parent=quest)
 add(npc,'Churano-Shurano','NPCs','Sells the Magicked Astrolabe needed for solo access through Eldieme gates.',section('Location',para('Windurst Waters North (F-8), on the Optistery roof beside the telescope.'))+section('Quest and reward',table(['Quest','Cost','Reward'],[(link(quest,'The Eldieme Necropolis Door Quest'),'10,000 gil',link(ki,'Magicked Astrolabe'))]))+sources,parent='npcs')
 note=section('Solo access: Eldieme gates',para('Before entering gated rooms, buy '+link(ki,'Magicked Astrolabe')+' from '+link(npc,'Churano-Shurano')+' at Windurst Waters North (F-8), on the Optistery roof, for 10,000 gil. '+link(quest,'Step-by-step directions')+'. This is an optional access aid, not a required turn-in item.'))
 for key,p in list(P.items()):
  if key in (quest,ki,npc):continue
  if key=='first-limit-break' or ('eldieme' in p['body'].lower() and p['category'] in ('Missions','Quests')):p['body']+=note
 P['quests']['body']=section('Dungeon access quests',table(['NPC','Quest','Reward'],[(link(npc,'Churano-Shurano')+' · Windurst Waters North (F-8)',link(quest,'The Eldieme Necropolis Door Quest'),link(ki,'Magicked Astrolabe')+' · costs 10,000 gil')]))+P['quests']['body']
 for key in ('npcs','items','travel'):
  if key in P:P[key]['body']+=section('Eldieme solo access',para(link(quest,'The Eldieme Necropolis Door Quest')+' · '+link(npc,'Churano-Shurano')+' · '+link(ki,'Magicked Astrolabe')))
