"""Retire Zenith equipment chapters; route equipment to native quest owners."""
from lxml import html
RETIRED=('an-edge-earned','hands-that-guard','stand-your-ground','hold-the-line','a-pair-of-quiet-blades','eyes-on-the-road','a-clean-recovery','a-shadows-safeguard','a-shadow-reforged','breakwater-crab')
def install(ed):
 P=ed.P;add,section,para,table,link,steps=ed.add,ed.section,ed.para,ed.table,ed.link,ed.steps
 oldtitles=[P[k]['title'] for k in RETIRED if k in P]
 for k,p in P.items():
  if k in RETIRED:continue
  root=html.fragment_fromstring(p['body'],create_parent='div')
  for a in list(root.xpath('.//a')):
   if a.get('href','').split('.')[0] not in RETIRED:continue
   row=next((r for r in a.iterancestors() if r.tag in ('tr','li')),None)
   if row is not None and row.getparent() is not None:row.getparent().remove(row)
   elif a.getparent() is not None:a.set('href','equipment-quests.html');a.text='Original equipment quests'
  p['body']=''.join(html.tostring(c,encoding='unicode') for c in root)
  # Historical update entries remain history, but cannot offer a retired quest.
  for f in ('intro','body'):
   p[f]=p[f].replace('Eight equipment chapters','Original equipment quests').replace('Steel & Shadow','Original equipment quests')
 for k in RETIRED:P.pop(k,None)
 status='World Quests v3.4.0 retires the custom WAR/THF chapters. Earned gear and saved progress are kept. Original quests remain with their native NPCs.'
 rows=[('Phara · Bastok Mines (J-9)',link('the-doorman','The Doorman'),'WAR 40+','Razor Axe'),('Brygid · Bastok Markets (K-9)',link('brygid-the-stylist','Brygid the Stylist'),'Wear Robe + Bronze Subligar','Gloves'),('Brygid · Bastok Markets (K-9)',link('brygid-the-stylist-returns','Brygid the Stylist Returns'),'Previous Brygid quest; wear an AF armor piece','Choose a level-50 body armor; provide its matching Subligar')]
 add('equipment-quests','Equipment Quests','Quests','Earn equipment from the original quests, alongside Auction House purchases, vendors, crafting and monster drops.',section('Where to begin',table(['NPC and game-map location','Quest','Requirement','Exact reward'],rows))+section('Artifact progression',para('The Doorman begins the Warrior AF route. Continue with Phara’s original follow-up quests. Other jobs use their own original AF quest lines. These are separate from Zenith’s retired equipment chapters.'))+section('Existing equipment',para('Keep all equipment and augments earned before this update. Retired custom chapters no longer accept objectives or award new items. No AF quest is auto-completed and no replacement reward is granted.')),parent='quests',status=status)
 add('the-doorman','The Doorman','Quests','The original Warrior artifact weapon quest.',section('Walkthrough',steps('Speak to Phara in Bastok Mines (J-9) on Warrior level 40 or higher. The native AF1 level setting still applies.','Go to the tents in Davoi (K-9)/(K-10). Find the Hide Flap and prepare for the two Orc NMs, Gavotvut and Barakbok.','Examine the Hide Flap to start the encounter. Defeat both enemies, then examine the relevant flap again to obtain Sword Grip Material.','Bring the material back to Phara. Return on the next Vana’diel day to receive Yasin’s Sword.','Deliver Yasin’s Sword to Naji in Metalworks (J-8). Your reward is Razor Axe.'))+section('Reward',para('1 Razor Axe. This uses the original item and quest; no Zenith augments are added.'))+section('Reference',para('<a href="https://horizonffxi.wiki/The_Doorman">HorizonXI: The Doorman</a>. Steps checked against the native Zenith source.')),facts=[('Starting NPC','Phara'),('Map location','Bastok Mines (J-9)'),('Main job','Warrior 40+; native AF1 setting'),('Reward','Razor Axe')],parent='equipment-quests')
 add('brygid-the-stylist','Brygid the Stylist','Quests','A short original equipment quest in Bastok.',section('Walkthrough',steps('Speak to Brygid in Bastok Markets (K-9).','Obtain a Robe and Bronze Subligar. Use a job that can equip both.','Wear both pieces and speak to Brygid again. She awards Gloves.'))+section('Reward',para('1 pair of Gloves. Keep the Robe and Bronze Subligar; the task checks what you wear.'))+section('Reference',para('<a href="https://horizonffxi.wiki/Brygid_the_Stylist">HorizonXI: Brygid the Stylist</a>.')),facts=[('Starting NPC','Brygid'),('Map location','Bastok Markets (K-9)'),('Required equipment','Robe + Bronze Subligar'),('Reward','Gloves')],parent='equipment-quests')
 add('brygid-the-stylist-returns','Brygid the Stylist Returns','Quests','Trade a Fomor Subligar for a selected body armor through Brygid’s original quest.',section('Requirements',para('Complete Brygid the Stylist first. Speak to Brygid while wearing an Artifact armor piece; an AF weapon alone does not qualify. The usual starting point is level 52+, when AF armor becomes equippable.'))+section('Walkthrough',steps('Speak to Brygid in Bastok Markets (K-9) while wearing your AF armor. Note the exact body and leg items she requests.','Obtain and wear the requested equipment, then return to her. Use the exact normal-quality pieces rather than their +1 versions.','Choose the body armor you want. She names the corresponding Subligar you must provide.','Hunt the appropriate Fomor in Phomiuna Aqueducts or Sacrarium for that Subligar. The drop is not guaranteed.','Trade the requested Subligar to Brygid with a free inventory slot to receive your selected armor.'))+section('WAR and THF choices',table(['Reward','Required item','Source'],[('Parade Cuirass · WAR/PLD','Pisces Subligar','Fomor Paladin'),('Rapparee Harness · THF','Gemini Subligar','Fomor Thief')]))+section('Reference',para('<a href="https://horizonffxi.wiki/Brygid_the_Stylist_Returns">HorizonXI: Brygid the Stylist Returns</a>. Other original body-armor choices remain available from Brygid.')),facts=[('Starting NPC','Brygid'),('Map location','Bastok Markets (K-9)'),('Reward','Selected original level-50 body armor'),('Repeatable','Yes')],parent='equipment-quests')
 for key,title in [('warrior-quests','Warrior Equipment Quests'),('thief-quests','Thief Equipment Quests'),('thief-equipment','Thief Equipment')]:
  body=section('Original equipment progression',para(link('equipment-quests','Original equipment quest directory')+'. Buy, craft or hunt for your other upgrades. Custom Zenith WAR/THF chapters are retired; earned equipment stays.'))
  body+=section('Recommended quest',para(link('the-doorman','The Doorman — Razor Axe, WAR 40+') if key=='warrior-quests' else link('brygid-the-stylist-returns','Brygid the Stylist Returns — Rapparee Harness for THF')))
  add(key,title,'Jobs','Use the original equipment quests and Artifact progression.',body,parent='equipment-quests',status=status)
 for key in ('zenith-armsmith','adventurer-log'):
  add(key,'Zenith Armsmith','NPCs','Equipment directions near Northern San d’Oria Home Point #1 (E-8).',section('Current role',para('The custom WAR/THF equipment chapters are retired. The Armsmith points you toward Phara in Bastok Mines (J-9) and Brygid in Bastok Markets (K-9). '+link('equipment-quests','Read the original quest guides')+'. Any unrelated legacy reward still awaiting collection remains available.'))+section('Other quest contacts',para('Trust progression stays with Gondebaud; Limit Break stays with Maat. City rings remain with their existing city contacts.')),parent='npcs',status=status)
 add('zenith-scout','Zenith Scout','NPCs','Field information beside the existing outpost books in Valkurm and Qufim.',section('Current role',para('Equipment-chapter reports and Breakwater Crab are retired. The Qufim quest marker at (F-6) still serves '+link('a-rhythm-worth-following','Uka Totlihn’s accepted quest')+'. Accept that quest from Gondebaud in Southern San d’Oria (L-6) first.')),parent='npcs',status=status)
 P['quests']['body']=section('Original equipment quests',table(['NPC and game-map location','Quest','Requirement','Reward'],rows))+P['quests']['body']
 P['update-log']['body']=section('Custom equipment chapters retired — v3.4.0',para('The eight early WAR/THF chapters and the later custom THF equipment quest are retired. Already earned items and augments are preserved. Equipment progression now points to original quests, AF, shops, crafting and monster drops. Native Phara/Brygid quests are verified without copying or replacing them. Trust, city-ring and national mission rewards remain unchanged.'))+P['update-log']['body']
 # Remove generic old instructions where another page still linked the former hub.
 for p in P.values():
  for f in ('intro','body'):
   p[f]=p[f].replace('Accept, review and claim equipment quests, Trust-slot journeys and Crystal Paths. Choose Quest details, Accept quest or Claim reward.','Equipment directions; original quest rewards come from their own NPCs.')
