from lxml import html
def install(ed):
 P=ed.P;add,section,para,table,link,steps=ed.add,ed.section,ed.para,ed.table,ed.link,ed.steps
 for key,p in P.items():
  if key=='update-log':continue
  root=html.fragment_fromstring(p['body'],create_parent='div')
  for e in list(root.xpath('.//tr|.//li|.//p')):
   text=e.text_content().lower()
   if ('armsmith' in text or 'automatically' in text and ('limit' in text or 'cap' in text) or 'no testimony' in text or 'free retries' in text) and e.getparent() is not None:e.getparent().remove(e)
  for e in list(root.xpath('.//div[@class="table-wrap"]')):
   if not e.xpath('.//tbody/tr') and e.getparent() is not None:
    prev=e.getprevious()
    if prev is not None and prev.tag=='h2':prev.getparent().remove(prev)
    e.getparent().remove(e)
  p['body']=''.join(html.tostring(c,encoding='unicode') for c in root)
 for key in ('zenith-armsmith','adventurer-log'):
  add(key,'Zenith Armsmith — Removed','Reference','This custom NPC has been removed from Northern San d’Oria.',section('Current services',para('Zenith Guide handles travel; Zenith Atlas handles EXP camps. '+link('equipment-quests','Original equipment quests')+' remain at their own NPCs. Earned items and saved records are not deleted.')),parent='retired-activities')
 rows=[('50 → 55','In Defiant Challenge','Trade Exoray Mold, Bomb Coal and Ancient Papyrus to Maat.'),('55 → 60','Atop the Highest Mountains','Collect the three Frigicite key items and return to Maat.'),('60 → 65','Whence Blows the Wind','Obtain the Orcish, Quadav and Yagudo Crests and return to Maat.'),('65 → 70','Riding on the Clouds','Follow Maat’s clues and trade Kindred’s Seals to the assigned NPCs.'),('70 → 75','Shattering Stars','Follow the original Testimony and battlefield quest, then return after victory.')]
 add('limit-break','Limit Break','Quests','Original Limit Break quests, with drop assistance for the first item hunt.',section('Quest progression',table(['Level limit','Original quest','Objective'],rows))+section('Starting NPC',para('Maat · Ru’Lude Gardens (H-5). Native eligibility and dialogue determine the quest offered. Expansion jobs retain their own final-trial NPCs.'))+section('First quest assistance',para(link('first-limit-break','First Limit Break hunting guide')+'. Original drops remain. A missing item is granted after the third eligible kill of its reviewed monster type, once.'))+section('Original final battle',para('The Testimony requirement and original battlefield entry checks are restored. No custom Accept final trial, Travel to trial or Unlock level 75 buttons.'))+section('Existing progress',para('Previously unlocked limits, completed quests and earned items remain. Future increases use original quests; no automatic increases.')),parent='character-progress')
 add('maat','Maat','NPCs','Original Limit Break quest giver.',section('Location',para('Ru’Lude Gardens (H-5).'))+section('Quests',para(link('limit-break','Original Limit Break stages and rewards')+'. Speak to him normally to accept or review the eligible quest. Trade required items through the game’s Trade action; original events handle completion.')),parent='npcs')
 add('first-limit-break','First Limit Break','Quests','In Defiant Challenge: collect three items for Maat to unlock level 55.',section('Accept',para('At level 50 with your limit still at 50, speak to Maat in Ru’Lude Gardens (H-5). Accept In Defiant Challenge through his original dialogue.'))+section('Hunting locations',table(['Item','Monster','Game-map location'],[('Exoray Mold','Exoray','Crawlers’ Nest: mushroom room (G-9)/(G-10)'),('Bomb Coal','Explosure','Garlaige Citadel: bomb-room map (I-8)'),('Ancient Papyrus','Lich','The Eldieme Necropolis: northwest tombs map (C-4)')]))+section('Drop assistance',para('Original drops remain random. After the third eligible kill of a reviewed monster of that type in the listed zone, its missing item is granted directly, once. Stay alive, in the same zone and within 50 yalms with valid kill credit. Trusts can help. Existing counters remain.'))+section('Full inventory',para('Free a slot, then speak to Maat, change zones or log in again to retry delivery. Discarding a guaranteed item does not grant a second guaranteed copy.'))+section('Trade and reward',steps('Put 1 Exoray Mold, 1 Bomb Coal and 1 Ancient Papyrus in your main inventory.','Trade exactly those three items together to Maat and complete his original event.','Reward: level limit 55 and the Horizon Breaker title. The three items are consumed.')),facts=[('NPC','Maat · Ru’Lude Gardens (H-5)'),('Reward','Level limit 55; Horizon Breaker title')],parent='limit-break')
 for key in ('quests','character-progress'):
  P[key]['body']=section('Original Limit Break progression',para(link('limit-break','Maat’s original quests, stages and rewards')+' — first-quest drop assistance remains.'))+P[key]['body']
  P[key]['body']=P[key]['body'].replace('Zenith Scout records equipment reports.','Qufim’s accepted Trust trial remains available.')
 P['roadmap']['intro']='World Quests v3.6.0 restores native Maat progression and removes Zenith Armsmith.'
 P['update-log']['body']=section('Native Maat and Armsmith removal — v3.6.0',para('Zenith Armsmith is removed. Maat uses original acceptance and turn-ins. Automatic cap increases, the custom trial menu and Testimony bypass are removed. The first Limit Break keeps its three-kill missing-item guarantee. Previously unlocked caps, completed quests and earned items are preserved. Travel, camps, rings and Trusts remain.'))+P['update-log']['body']
