"""Scout locations from delivered placement variants, not a live server claim."""
from html import escape

def install(ed):
    P,add,link,para,section,table,steps=ed.P,ed.add,ed.link,ed.para,ed.section,ed.table,ed.steps
    location_table=table(['Zone / layout','In-game map','Where to look','Nearby landmark'],[
        (link('zone-valkurm-dunes','Valkurm Dunes')+' — Scout By Books v1.0','<a href="zenith-scout.html#valkurm-dunes-map">H-7 · marked map</a>','On the approach side of Field Manual and Survival Guide, about 4 and 5.4 yalms from the books respectively. Requires the replacement package and a server restart.','<code>H-7</code>'),
        (link('zone-qufim-island','Qufim Island')+' — Qufim Wall layout','<a href="zenith-scout.html#qufim-island-map">F-6 · marked map</a>','At the Delkfutt’s Tower / outpost staging area, beside Zenith Atlas along the wall.','<code>F-6</code>'),
    ])
    alert='<div class="scout-alert">'+para('<strong>New Valkurm placement: beside Field Manual and Survival Guide.</strong> The Scout By Books v1.0 package changes the spawn point to <code>H-7</code>. Stop the server, install the package and restart it to create one Scout at this point. Quest progress and the Qufim Scout are preserved; no GM account is needed.')+para('The uploaded runtime report on 19 September at 13:57–13:58 UTC confirmed one normal Scout at the previous <code>H-7</code> position, including after player entry. The source audit and both <code>Zone.lua</code> hooks were also reviewed. The replacement was then requested because the old location remained difficult to find. Terrain and creation checks passed offline; visibility at the new point has not yet been confirmed in the player’s client.')+'</div>'
    def figure(zone,alt,markers,caption):
        overlay=''.join(f'<span class="scout-marker{cls}" style="left:{x/512*100}%;top:{y/512*100}%;width:{w/512*100}%;height:{h/512*100}%" aria-hidden="true"></span>' for cls,x,y,w,h in markers)
        return f'<figure class="scout-map"><div class="map-marked"><img src="assets/maps/{zone}.png" width="512" height="512" alt="{escape(alt)}" loading="lazy">{overlay}</div><figcaption>{caption}</figcaption><button type="button" data-enlarge-map>Enlarge marked map</button> · <a href="assets/maps/{zone}.png">Original map</a></figure>'
    valkurm=figure('valkurm-dunes','Valkurm Dunes: red H-7 outpost cell for the Scout By Books replacement, beside Field Manual and Survival Guide',[
        ('',240,208,32,32)],
        '<span class="scout-key"></span><strong>H-7: Scout By Books replacement.</strong> Find Field Manual and Survival Guide at the outpost. The replacement point is on their approach side. Red marks the outpost grid cell, not an exact NPC pixel.<br><a href="https://horizonffxi.wiki/Valkurm_Dunes">Original zone and map reference</a>. Original game map © SQUARE ENIX; map annotations credited on the image. The colored overlay is this wiki’s landmark guide.')
    qufim=figure('qufim-island','Qufim Island: red F-6 cell at the outpost and Delkfutt staging area',[('',176,176,32,32)],
        '<span class="scout-key"></span><strong>F-6: Qufim Wall layout.</strong> Approach the wall near Zenith Atlas. Red marks the relevant grid cell, not an exact NPC pixel.<br><a href="https://horizonffxi.wiki/Qufim_Island">Original zone and map reference</a>. Original game map © SQUARE ENIX; map annotations credited on the image.')
    report_steps=steps('Accept your level-25 equipment chapter from Zenith Armsmith after fully collecting the preceding chapter’s reward. Stay on the matching main job at level 25 or above.','Find Zenith Scout in Valkurm Dunes. Stand within six yalms, out of combat, and select <strong>Record scout report</strong>. Opening Current assignment alone does not record it.','Repeat <strong>Record scout report</strong> at the Qufim Island Scout. Each report counts only for the active WAR or THF track.','Defeat the six chapter targets in Qufim Island: Clippers for WAR, Land Worms for THF. Reports and kills may be done in either order after acceptance.','Use Current assignment to confirm Valkurm 1/1, Qufim 1/1 and Targets 6/6. Return to Zenith Armsmith to collect the reward.')
    troubleshoot=ed.listing([
        '<strong>Replacement layout:</strong> install Scout By Books v1.0 with the server stopped, then restart. The previous dynamic NPC ends with the old map process; the next startup creates one at the new point. Job and level checks control menu actions, not Scout creation.',
        '<strong>Scout visible, report option missing:</strong> confirm WAR25+ or THF25+ is your main job, the corresponding level-25 chapter is accepted, and that zone’s report is not already 1/1. WAR and THF reports are separate.',
        '<strong>No interaction:</strong> stand close, leave combat and clear aggro. The reviewed menu checks a six-yalm range and the registered NPC identity.',
        '<strong>Verified runtime baseline:</strong> both zones completed initialization and had one normal Scout in the uploaded report. The new package changes only the Valkurm position data. It does not add a second creation hook or require a GM command.',
        'Do not reset quest progress, delete character variables or reinstall old packages to diagnose a missing NPC. This wiki update does not change the game server.',
    ])
    provenance=para('Replacement placement: Field Manual is at H-7; Survival Guide is at H-7 in the pinned native NPC data. The replacement Scout at H-7 is approximately 4.0 and 5.4 yalms from those books. The center and 72 nearby navigation samples are walkable. This is an offline terrain check; appearance in the player’s client remains unverified.')+para('Runtime evidence: the uploaded report records successful initialization in both zones at 13:57:57 UTC on 19 September, with one normal Scout per zone. It records the Valkurm Scout again after player entry at 13:58:35. This establishes server-side existence at the old point, not why the player could not see it.')+para('Earlier source audit: six files collected at 13:13:43 UTC matched their reported hashes. Both Zone.lua hooks were present. The outpost hash below describes the data before Scout By Books v1.0; the replacement changes only the Valkurm position line. The older entrance variants are historical comparison only.')+table(['Earlier position variant','Payload SHA-256'],[
        ('Valkurm outpost; Qufim wall','<code>2cdcc8b2e1164a7ed95094c256d830705ccecc2a4687a568a951f062c3275e75</code>'),
        ('Valkurm entrance, original offset; Qufim wall','<code>8df99d020a4aeebd45a2d3021d362d9362e2d3f881837807ee360950281361ad</code>'),
        ('Valkurm entrance, adjusted offset; Qufim wall','<code>29dfa966a49dccd22513f3d11ad08588a3d1c1ec329e336c35938d64fc56534a</code>'),
    ])+para('H-7 and F-6 identify map landmarks corroborated by the original zone references. They are source-based areas to check, not evidence that the custom NPC is currently visible on the live server.')
    add('zenith-scout','Zenith Scout','NPCs','The field contact for WAR and THF equipment quests in Valkurm Dunes and Qufim Island.',alert+section('Locations by zone',location_table)+section('Valkurm Dunes map',valkurm)+section('Qufim Island map',qufim)+section('Record both level-25 reports',report_steps)+section('Cannot find the Scout or report option',troubleshoot)+section('Level-35 encounter',para('Only the Qufim Scout starts '+link('breakwater-crab','Breakwater Crab')+' for an accepted level-35 chapter. The Scout does not accept equipment quests or hand out rewards.'))+section('Placement evidence',provenance),facts=[('Valkurm','H-7, beside Field Manual and Survival Guide after Scout By Books v1.0'),('Qufim','F-6 staging area'),('Report requirement','Active WAR25+ or THF25+ chapter'),('Quest giver',link('zenith-armsmith','Zenith Armsmith'))],parent='npcs',status='Scout By Books v1.0 prepares a new Valkurm point. Installation and restart are required; client visibility is unverified.')
    for job,key,title,previous,targets,reward in [
        ('WAR','hands-that-guard','Hands That Guard','An Edge Earned','Clippers','Chain Mittens with Accuracy +2 and Attack +2.'),
        ('THF','eyes-on-the-road','Eyes on the Road','A Pair of Quiet Blades','Land Worms','Beetle Mittens with DEX +1 and Accuracy +2.'),
    ]:
        body=section('Requirements',ed.listing([job+' as your main job, level 25 or above.','Finish '+previous+' and fully collect its reward.','Accept this chapter at Zenith Armsmith before recording reports or kills.']))
        body+=section('Walkthrough',steps('Visit Zenith Armsmith near Home Point #1 in Northern San d’Oria on '+job+'25+. Choose Equipment quests → Accept quest. Older menus call this Accept this chapter.','After Scout By Books v1.0, find the Valkurm Scout beside Field Manual and Survival Guide at the H-7 outpost. Choose Record scout report and confirm Valkurm 1/1.','Find the Qufim Scout at F-6 near the Delkfutt / outpost staging wall. Choose Record scout report; confirm Qufim 1/1.','Defeat 6 '+targets+' in Qufim Island while alive, nearby and on '+job+'25+. No specific weapon is required for this chapter.','Check Current assignment for both reports and Targets 6/6. Return to Armsmith: Equipment quests → Claim reward. Older menus call this Finish / collect reward.'))
        body+=section('Scout locations',location_table)+alert+para(link('zenith-scout','Open the marked maps and missing-Scout checklist.'))
        body+=section('Marked maps',valkurm+qufim)+section('Reward',para(reward))+section('Credit and menu notes',para('Reports and kills can be completed in either order after acceptance. Earlier kills do not count. Trust and party assistance count when you qualify, even if the target gives no EXP. WAR and THF progress are separate. If your inventory is full, make room and collect the pending reward without repeating the quest.'))
        add(key,title,'Quests','Collect both field reports and defeat six '+targets+' to earn your '+job+' level-25 equipment reward.',body,[('Starting NPC',link('zenith-armsmith','Zenith Armsmith')),('Main job',job+'25+'),('Reports','Valkurm 1/1 + Qufim 1/1'),('Targets','6 '+targets),('Reward',reward)],parent='warrior-quests' if job=='WAR' else 'thief-quests',status='Menu names depend on the installed revision. Scout map areas come from reviewed package layouts; live visibility is not confirmed.')
    for key in ['equipment-quests','warrior-quests','thief-quests','breakwater-crab','zone-valkurm-dunes','zone-qufim-island']:
        P[key]['body']+=section('Scout location guide',para(link('zenith-scout','Zenith Scout: current placement package, marked maps and source evidence.')+' Scout By Books v1.0 places the Valkurm Scout beside Field Manual and Survival Guide at H-7 after installation and restart. Qufim remains at the F-6 staging area.'))
    P['update-log']['body']=section('Scout source check — 19 September, 13:13 UTC',para('The follow-up collection contains both Zone.lua files and the four supporting Lua files. All hashes were verified. Both Scout initialization hooks are present; the Valkurm outpost coordinates remain unchanged. The callbacks passed an isolated LuaJIT composition check with mocked engine APIs. Map-server startup output and live NPC state are still needed; no cause, server fix or restored Scout visibility is claimed.'))+section('Scout investigation correction',para('The earlier source audit identified the Qufim Wall outpost payload. Guidance to search the La Theine entrance was withdrawn for this installation. The missing zone files from that first audit have now been reviewed.'))+section('Wiki update: missions and Scout maps',ed.listing(['Three national story directories, with 60 individual mission guides from Rank 1 to Rank 10, nation images and selected route maps.','WAR25 and THF25 guides include the separate Record scout report action and marked map areas.','A missing Valkurm Scout was reported. No game files were changed and live visibility remains unverified.']))+P['update-log']['body']
    P['update-log']['body']=section('Valkurm Scout replacement beside the books',para('The runtime report confirmed one normal Scout at the previous location after player entry. At the player’s request, Scout By Books v1.0 now prepares a replacement at H-7, beside Field Manual and Survival Guide. A full map-server restart creates the replacement from the updated data. Quest state and Qufim are preserved. Placement was reviewed against the native books and pinned navigation surface; live-client appearance remains to be confirmed.'))+P['update-log']['body']
    P['sources']['body']+=section('Mission and Scout map references',para('National walkthroughs link to their individual HorizonXI pages and pinned LandSandBoat definitions. Nation city images come from PlayOnline. Route maps retain the original on-image credits and link to their source file pages. Scout map highlights show documented landmarks and explicitly labeled approximate areas; they are not live NPC tracking.'))
